---
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:80/tcp"
    environment:
      - "TZ=${TZ}"
      - "FTLCONF_webserver_api_password=${FTLCONF_webserver_api_password}"
      - "FTLCONF_dns_listeningMode=all"
      - "FTLCONF_dns_upstreams=unbound#5335"
    volumes:
      - "./config/pihole/:/etc/pihole/"
    restart: unless-stopped

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    hostname: unbound
    volumes:
      - "./config/unbound/:/opt/unbound/etc/unbound/"
    restart: unless-stopped
